on:
  issues:
    types:
      - labeled

jobs:
  run_if_label_matches:
    if: github.event.label.name == 'PUBLISH' || startsWith(github.event.label.name, 'PUBLISH_')
    runs-on: ubuntu-latest
    steps:
      - run: echo 'it works'
